### ISSUE TITLE
Delegate methods to get player events

### ISSUE THREAD

**Issue by artem-shmatkov** [kinescope/ios-kinescope-player#3]
At least for play/pause/loading/fullscreen_on/fullscreen_off

**Comment by fedulvtubudul** [comment]
While debugging unreliable player behaviour I was looking for a way to track its status. And was surprised to see this declaration in `KinescopeVideoPlayer.swift`:

```swift
    private weak var delegate: KinescopeVideoPlayerDelegate?
```

I see no reason to declare delegate as `private` property. How can I use it from application code?

**Comment by NullIsOne** [comment]
It was really a mistake to make delegate private. 
But anyway `KinescopeVideoPlayerDelegate` have very limited amount of methods implemented.

For debug purposes there is also `KinescopeDefaultLogger` exists which cover a lot more events in playerView and player itself.

Could you clarify, do you still need to listen some events through delegate? It would be great if you prepare a list of events to listen.

**Comment by NullIsOne** [comment]
Fixed in https://github.com/kinescope/ios-kinescope-player/releases/tag/0.2 
Now you can set `KinescopeVideoPlayerDelegate` or `KinescopeAnalyticsDelegate`
